### ISSUE TITLE
Goal release is not pushing the new tag and version changes to remote for git

### ISSUE THREAD

**Issue by jasonfungsing** [smh/grunt-maven-tasks#24]
Hi there,

We are using bamboo, nexus and git for release. I have configure bamboo to checkout the code from remote git, then do the build/release which should including step upload artifacts to nexus, create new tag in git, update new version with snapshot keyword. It is all working good, however the last step which is push the changes(new version tag and new snapshot keyword changes) are not push back to git remote.

Am I missing something or this is not a function currently available?

Thanks

**Comment by swisstofu** [comment]
hello, as i had the same need, i've created a PR to add an option "gitpushtag". would it be possible to review it ? thanks

**Comment by smh** [comment]
Thanks! Merged

**Comment by swisstofu** [comment]
great thanks!
