### ISSUE TITLE
Make the src part of global options

### ISSUE THREAD

**Issue by rraziel** [smh/grunt-maven-tasks#28]
Hello,

Right now the src property has to be set on goals individually:

```
options: {
    src: ['dist/**']
}
```

The result is an empty zip. Which means I have to do this:

```
options: {
    ...
},
install: {
    src: ['dist/**']
},
deploy: {
    src: ['dist/**']
},
release: {
    src: ['dist/**']
}  
```

It would be nice if the goals picked the src from the global options (specifying a src in the goal would obviously override the global setting).

**Comment by lglussen** [comment]
I too would like to see this.
