### ISSUE TITLE
How to run 'mvn clean install' from gruntfile?

### ISSUE THREAD

**Issue by sthang** [smh/grunt-maven-tasks#31]
I have a Javascript project that uses Grunt to build. As part of the grunt tasks, I need to build and package a Java project which uses Maven. Here's the folder structure of my project

_javascript-project
  *_js-src(contains js files)
  **external
      **_agents(contains java mvn project)
           *_**src
           ***_pom.xml(this needs to be built)
  *_Gruntfile.js
  *_package.json
  *_pom.xml(dummy placeholder for javascript project)

To build this javascript project we use grunt install. Now as part of this grunt install, I need to build the mvn project under external folder. I do not need to deploy or release it to any remote repository. I just need to build it locally. Here's the sample of Gruntfile.js

 // Project configuration.
    grunt.initConfig({
         ...(normal tasks to build js files)
         maven: {
            options: {
                debug: 'true',
                goal: 'install',
                groupId: 'org.example',
                url: '<repository-url>'
            },
            src: [ 'external/agents/**', '' ]
        }
    });

 grunt.loadNpmTasks('grunt-maven-tasks');

 grunt.registerTask('install', ['maven']); 

Can you help me to run 'mvn clean install' on the external agent folder when 'grunt install' is run on the Javascript project?

**Comment by erikgb** [comment]
@sthang : I suggest an alternative solution to your issue; invoke the Grunt build as part of your Maven build. We have been using this Maven plugin to achieve exactly that: https://github.com/eirslett/frontend-maven-plugin. There are other alternatives too...
