### ISSUE TITLE
Add uniqueVersion parameter to maven-deploy

### ISSUE THREAD

**Issue by sonytricoire** [smh/grunt-maven-tasks#39]
Add a parameter to enable/disable maven deploy options (-DuniqueVersion=false) that adds a timestamp to an artifact.

**Comment by smh** [comment]
I am happy to accept a pull-request for this feature, however I do not have the time to implement this myself.

**Comment by GregDThomas** [comment]
I see https://github.com/smh/grunt-maven-tasks/pull/42 fixes this; any chance of getting a release out to include this feature? Thanks!

**Comment by smh** [comment]
Certainly, I will see if I can get this out tonight when I get back home

**Comment by smh** [comment]
new version published

**Comment by GregDThomas** [comment]
Hmm, it seems that the patch isn't working; 7d5a612 seems to have backed out the change again. I'll see if I can submit a new patch for this shortly.
