### ISSUE TITLE
Packaging tgz outputs a zip file, not a gzipped tarball

### ISSUE THREAD

**Issue by jpmeyer** [smh/grunt-maven-tasks#45]
Commit 913010720ddf26008bb769170ef3a86677e5e31c forces compress mode of zip for all artifacts, even those that are not zip files. The original packaging from the options needs to be passed as the mode to the grunt-contrib-compress options

**Comment by JudeAntony** [comment]
+1. 
Is there any fix / work around ?

**Comment by karthilxg** [comment]
Package created with the following grunt configs produces a `.tgz` file which was not a valid `.tgz` format, unable to unpack with `maven` as it complains not a valid format.

```javascript
 maven: {
        options: {
            groupId: 'com.sample.hello',
            artifactId: 'hello-world',
            packaging: 'tgz',
            classifier: 'distrib',
            injectDestFolder: 'false'
        },
        package: {
            goal: 'package',
            expand: true,
            cwd: 'dist/',
            src: ['**/*'],
            dest: '/',
            dist: 'target'
        }
}
```

Maven unable to unpack:

```sh
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack (unpack) on project sample: 
Error unpacking file: 
/Users/sample/.m2/repository/com/sample/hello/hello-world/1.0.0-SNAPSHOT/hellow-world-1.0.0-SNAPSHOT-distrib.tgz  to: /Users/something/

[ERROR] org.codehaus.plexus.archiver.ArchiverException: 
Error while expanding /Users/sample/.m2/repository/com/sample/hello/hello-world/1.0.0-SNAPSHOT/hellow-world-1.0.0-SNAPSHOT-distrib.tgz: Not in GZIP format
```

**Comment by jpmeyer** [comment]
I have a PR with multiple fixes in a fork. Many of the issues are rather old, so if the maintainer is not active, you can apply those fixes in your grunt/npm project by setting the version of grunt-maven-tasks to https://github.com/jpmeyer/grunt-maven-tasks/tarball/47628db580e5a59c091b2e951fbb699096090a08.

**Comment by karthilxg** [comment]
@jpmeyer Able to unpack it successfully with the forked version 👍  thanks !!!
